# Generated by Django 2.0.5 on 2018-06-22 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_auto_20180622_0613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libraries',
            old_name='libraries',
            new_name='library',
        ),
    ]
